// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bigbmcrwnkgegupqiyst.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJpZ2JtY3J3bmtnZWd1cHFpeXN0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUzOTc3MTEsImV4cCI6MjA2MDk3MzcxMX0.lfLzAHD3a5JgzdqnunyGxhLtck1hiBvHtuVI2GH3Rdo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);